services:
#    App\User\Controller\:
#        resource: '../src/User/Controller'
#        tags: ['controller.service_arguments']

    App\User\Service\Test:
        arguments:
            $message: 'user_key_translate'